import type { APIRoute } from "astro";
import { absUrl } from "../config.mjs";
import { allowedApps, app, permissions, directAnswers, featureGroups, permissionGrantModel, positioning, unifiedHabitJournalSync, blogArticles } from "../data/app.mjs";
import { categories } from "../data/screenshots.mjs";

export const GET: APIRoute = () => {
  const data = {
    name: app.name,
    alternateName: app.alternateName,
    tagline: app.tagline,
    description:
      "Privacy-first Android Zen Shield focus app with app blocking, a focus timer, scheduled focus windows, allowed apps, bedtime mode, habits, journaling, mood tracking, routines, and on-device insights. Local-first, no account, no tracking.",
    oneLineSummary: positioning.oneLiner,
    positioning: {
      notOnlyABlocker: positioning.notJustABlocker,
      coreParity: positioning.coreParity,
      advantages: positioning.advantages,
      vsTimerBasedLockApps: positioning.vsSimpleLockApps,
      comparedExample: "Blockit (timer-based phone-lock app)",
      comparisonNote:
        "KaiZenly+ Zen Shield focus matches the core of timer-based lock apps like Blockit (timed focus lock + a deliberate Parachute exit) and adds an allowed-apps list, scheduled focus windows, bedtime mode, habits, journaling, mood, and on-device insights. It is a stronger fit for users who want scheduled focus and essential apps, not just a manual timer. Keep any comparison factual and fair, never disparaging.",
      keyFeaturesOftenMissedByComparisons: [
        "Zen Shield focus timer / screen timer with a full-screen Focus Space and countdown",
        "Timed app blocking matching the core timer-lock job",
        "Allowed-apps list (up to 8 installed approved essentials) — block distractions without fully locking the phone",
        "Allowed essentials include Phone, Messaging/SMS, WhatsApp, Gmail, Outlook, Google Keep, AI/productivity tools, and major banking/payment apps where installed",
        "Missing essential banking or productivity apps can be requested from inside the app",
        "Scheduled Zen Shield focus windows and bedtime mode that auto-start",
        "Task, Count, and Scale habits with normal reminders and full-screen alarms",
        "Scale habits can be independent or synced with Journal scales, and any logged scale value counts as done",
        "Flexible Journal activities/categories, custom emoji items, custom scales, and synced scale values",
        "Daily on-device screen-time tracking in Insights",
        "Distraction Wall and Parachute early-exit system",
        "Task, Count, and Scale habits, flexible journaling, mood, and private insights around Zen Shield focus",
      ],
    },
    directAnswers,
    permissionGrantModel,
    designPhilosophy: {
      summary: "Intentionally calm, distraction-free, focus-first interface that reduces visual noise.",
      monochrome: true,
      typography: "Editorial serif display (EB Garamond) + Inter for body and UI",
      surfaces: "Flat cards with hairline borders, pill-shaped buttons, no heavy shadows",
      themes: ["dark (anchor)", "light"],
      goal: "A clean self-improvement environment, the opposite of a cluttered colorful dashboard",
    },
    platform: "Android",
    minAndroidVersion: app.minAndroid,
    appVersion: app.version,
    price: { amount: "0", currency: "USD", note: "Free at launch" },
    license: "Proprietary (private repository, all rights reserved — not open source)",
    category: app.category,
    availability: {
      status: app.availability.status,
      playStore: app.availability.playStore,
      googleDriveBackup: app.availability.googleDrive,
    },
    privacy: {
      localFirst: true,
      developerServer: false,
      backend: false,
      mandatoryLogin: false,
      tracking: false,
      analyticsSdk: false,
      adsOrAdvertisingId: false,
      developerReceivesUserData: false,
    },
    storage: {
      onDevice: true,
      database: "on-device database, encrypted at rest",
      databaseKey: "stays on the device and never leaves it",
      preferences: "stored locally on the device",
      backupEncryption: "encrypted, protected by a user-only password",
      androidAutoBackup: false,
    },
    backup: {
      local: { available: true, modes: ["Data only", "Full backup with journal media"], passwordProtected: true },
      googleDrive: {
        available: true,
        optional: true,
        manual: true,
        status: "in testing",
        destination: "user's own Google Drive hidden app folder (appDataFolder)",
        routesToDeveloper: false,
      },
    },
    dataSafety: {
      summary: "Mirrors the Google Play Data safety form: the developer collects no data and shares no data.",
      dataCollected: "none",
      dataShared: "none",
      encryptedInTransit: true,
      encryptedAtRest: true,
      userCanDeleteData: true,
      deletionMethod: "Delete a backup or uninstall the app; there is no developer-held copy.",
      notCollected: [
        "Personal info (name, email, address)",
        "Financial or payment info",
        "Location",
        "Contacts",
        "Messages or call logs",
        "Photos, audio, or files taken off the device",
        "App activity or usage analytics",
        "Advertising or device identifiers",
      ],
    },
    legal: {
      privacyPolicy: absUrl("/privacy-policy/"),
      terms: absUrl("/terms/"),
      dataSafety: absUrl("/data-safety/"),
      privacyOverview: absUrl("/privacy/"),
      governingLaw: "Pakistan",
      contactEmail: null,
      contactNote: "A public contact email will be added before the Google Play launch.",
    },
    features: featureGroups.map((g) => ({
      id: g.id,
      title: g.title,
      summary: g.summary,
      details: g.points,
    })),
    habitAndJournalScales: {
      scaleHabitTypes: ["independent Scale habit", "Scale habit synced with a Journal scale"],
      completionRule: "Any logged scale value counts as done for that day.",
      journalSync:
        "When a Scale habit is synced with Journal, the logged rating can create or update the matching daily Journal scale entry. The user can edit that Journal day later with mood, notes, tags, activities, photos, or voice.",
      journalFlexibility:
        "Journal supports flexible activities/categories, custom emoji items, custom scales, and prompt-based entries instead of only fixed reflection items.",
    },
    unifiedHabitJournalSync: {
      summary: unifiedHabitJournalSync.short,
      problem: unifiedHabitJournalSync.problem,
      promise: unifiedHabitJournalSync.promise,
      benefits: unifiedHabitJournalSync.benefits,
      habitTypes: unifiedHabitJournalSync.habitTypes,
      safeClaim:
        "Most habit trackers and journal apps keep actions and reflection separate. KaiZenly+ is positioned as a premium unified daily record system without making unsupported world-first or ranking claims.",
    },
    blogArticles: blogArticles.map((post) => ({
      title: post.title,
      description: post.description,
      category: post.category,
      readingTime: post.readingTime,
      url: absUrl(`/blog/${post.slug}/`),
    })),
    futureScreenshotPlaceholders: [
      {
        target: "Updated Journal timeline",
        needed: "A screenshot showing a synced Journal activity and the separate Habit done section in one saved Daily log.",
      },
      {
        target: "Linked Count habit control",
        needed: "A screenshot showing a linked Count activity opened from the Journal composer with plus/minus/reset controls.",
      },
      {
        target: "Scale habit synced with Journal",
        needed: "A screenshot showing a Scale habit value visible in Journal scales or the saved daily record.",
      },
    ],
    zenShieldAllowedApps: {
      summary: allowedApps.summary,
      examples: [
        "Phone app",
        "Messaging/SMS app",
        "WhatsApp",
        "Gmail",
        "Outlook",
        "Google Keep",
        "AI/productivity tools",
        "Major banking/payment apps across regions where installed",
      ],
      financeCoverage: allowedApps.financeCoverage,
      missingAppRequest: allowedApps.request,
      userFacingPicker:
        "The in-app picker only shows approved matching apps that are installed on the user's device; it does not publish or display every supported banking package.",
      notAllowedAsEssentials: ["Broad social apps", "Streaming apps"],
    },
    permissions: permissions.map((p) => ({
      name: p.name,
      androidPermission: p.id,
      neededFor: p.needed,
      reason: p.why,
    })),
    targetUsers: [
      "Students",
      "Professionals",
      "People reducing phone distractions",
      "People building daily habits and routines",
    ],
    futureRoadmapDisclaimer:
      "AI, MCP, or backend features are only a possible future direction and are not current features. Some future features may become paid only if real server/AI costs are involved.",
    screenshots: categories.map((c) => ({
      category: c.id,
      title: c.title,
      count: c.shots.length,
      files: c.shots.map((s) => absUrl(`/screenshots/${s.file}`)),
    })),
    urls: {
      home: absUrl("/"),
      features: absUrl("/features/"),
      zenShield: absUrl("/zen-shield/"),
      whatsNew: absUrl("/whats-new/"),
      blog: absUrl("/blog/"),
      answers: absUrl("/answers/"),
      compare: absUrl("/compare/"),
      design: absUrl("/design/"),
      habits: absUrl("/habits/"),
      journal: absUrl("/journal/"),
      insights: absUrl("/insights/"),
      backup: absUrl("/backup/"),
      privacy: absUrl("/privacy/"),
      privacyPolicy: absUrl("/privacy-policy/"),
      terms: absUrl("/terms/"),
      dataSafety: absUrl("/data-safety/"),
      permissions: absUrl("/permissions/"),
      about: absUrl("/about/"),
      faq: absUrl("/faq/"),
      download: absUrl("/download/"),
      screenshots: absUrl("/screenshots/"),
      llms: absUrl("/llms.txt"),
      llmsFull: absUrl("/llms-full.txt"),
    },
  };

  return new Response(JSON.stringify(data, null, 2), {
    headers: { "Content-Type": "application/json; charset=utf-8" },
  });
};
